name: Auto Pay Job

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 09:00 KST (UTC 기준 00:00)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 캐시된 패키지 복원
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip  # pip 캐시 경로
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}  # requirements.txt 파일의 해시값을 키로 사용
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 의존성 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo apt-get install xclip
          sudo apt-get install -y xvfb
          pip install -r requirements.txt  # requirements.txt를 사용해 패키지 설치

      - name: .env 파일 생성
        run: |
          echo "ID=${{ secrets.ID }}" >> .env
          echo "PW=${{ secrets.PW }}" >> .env
          echo "KAKAO_ID=${{ secrets.KAKAO_ID }}" >> .env
          echo "KAKAO_PW=${{ secrets.KAKAO_PW }}" >> .env
          echo "CARD_NUM=${{ secrets.CARD_NUM }}" >> .env
          echo "CARD_NAME=${{ secrets.CARD_NAME }}" >> .env
          echo "CARD_BIRTH=${{ secrets.CARD_BIRTH }}" >> .env
          echo "PAY_AMOUNT=${{ secrets.PAY_AMOUNT }}" >> .env

      - name: 셀레니움 그래픽 환경 설정
        run: |
          # Xvfb를 백그라운드에서 실행
          nohup Xvfb :99 -screen 0 1280x1024x24 &
  
          # 디스플레이 환경 변수 설정
          export DISPLAY=:99


      - name: 자동 결제 스크립트 실행
        env:
          DISPLAY: ':99'
        run: python test.py
